### ISSUE TITLE
Erro ao atualizar tarifas em lote

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling7#222]
Olá.

Está ocorrendo um problema ao atualizar tarifas em lote. Seleciono algumas e tento trocar o STATUS para INATIVO e esse erro aparece:

Technical information: CDbCommand falhou ao executar o comando SQL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'module' in 'where clause'
--

**Comment by magnussolution** [comment]
atualiza
