### ISSUE TITLE
Menu Configuração com problema na Pagina 2

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling7#303]
O Menu de configuração não apresenta a pagina 2 na ultima versão 6.7.2
![p1](https://user-images.githubusercontent.com/28572532/63747088-b1714080-c87c-11e9-8e0f-1431afff7f86.jpg)
![p2](https://user-images.githubusercontent.com/28572532/63747089-b209d700-c87c-11e9-8d5f-f902ba2ececb.jpg)

**Comment by magnussolution** [comment]
por favor repetir o teste, provavelmente a sessao expirou, pois nao consegui simular.

**Comment by yurikurka** [comment]
Não expirou não, foi limpo caches e cookies e a página 2 continua não sendo
demonstrada. Essa máquina de testes sofreu dois updates somente,  Vou
efetuar uma instalação nova para ver se acontece.

Em ter, 27 de ago de 2019 08:44, Adilson Magnus <notifications@github.com>
escreveu:

**Comment by yurikurka** [comment]
Segue o video instalacao zerada. Mesmo problema

[2019-08-27 15-06-35.zip](https://github.com/magnussolution/magnusbilling6/files/3547504/2019-08-27.15-06-35.zip)

**Comment by itsshimmer** [comment]
![chrome_YuChcyrDXE](https://user-images.githubusercontent.com/34427420/63797425-71db4080-c8de-11e9-845c-d84f6abfbd17.png)
