### ISSUE TITLE
session hijacking - arbitrary login without password

### ISSUE THREAD

**Issue by osekom** [magnussolution/magnusbilling7#383]
**Describe the bug**
The process of registering a user in the system sends a confirmation email to my account, the link I am receiving returns my id in the database

example:
http://test.example.com/mbilling/index.php/signup/{id}

When confirming my email, the code returns me to my session without having to use my password, this is where the security flaw occurs if you change the id for some other database id and enter it in the link that you mention as an example. This will return a "valid" session without having entered the user's password.

**To Reproduce**
1. Go to registration
2. Click on link confirm my account

**Expected behavior**
validation return with password

**Screenshots**
https://postimg.cc/9Dvp6pzV

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: >= 7

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version: >= 7

**Additional context**
I work for a group of companies in computer security, therefore investigating this type of situation is obtained regularly, I am not interested in any of your data and my ethics as a professional and moral always notified the system administrators of the security failure. I have a blog where I concurrently write these failures found, with this request you requested directly in writing a confirmation of being able to write this event on my blog without any legal situation or image damage to you.

**Comment by magnussolution** [comment]
hi, we found and fix the issue. Thanks per report. Please update your server to get the last update
