### ISSUE TITLE
Campo CODEC somente é exibido como NULL no CHAMADAS ONLINE

### ISSUE THREAD

**Issue by GabrielBragaGit** [magnussolution/magnusbilling7#408]
Versão 7.4.4

No Chamadas Online o CODEC das ligações não é exibido na lista, mesmo com o status da chamada em 'UP', porém se clicar na chamada o CODEC aparece nos detalhes.

**Comment by magnussolution** [comment]
pkill -f callchart 

e aguarde

**Comment by GabrielBragaGit** [comment]
Ja foi feita essa tentativa... o que não é exibido é somente o CODEC, a ligação aparece normalmente mas na coluna do CODEC só aparece NULL.
